Repository statisticsnorway/ssb-sirius-dash, pull requests merged in 2024-12, with the labels that each got.

#102 Setter opp docs
  docs/index.md
  docs/komme_i_gang.md
  docs/reference.md
  src/ssb_sirius_dash/control/framework.py
  src/ssb_sirius_dash/modals/hb_method.py
  src/ssb_sirius_dash/modals/kontroller.py
  src/ssb_sirius_dash/modals/kvalitetsindikatorer.py
  src/ssb_sirius_dash/modals/modal_functions.py
  src/ssb_sirius_dash/modals/visualiseringsbygger.py
  src/ssb_sirius_dash/setup/app_setup.py
  src/ssb_sirius_dash/setup/functions.py
  src/ssb_sirius_dash/setup/main_layout.py
  src/ssb_sirius_dash/setup/variabelvelger.py
  src/ssb_sirius_dash/tabs/aarsregnskap.py
  src/ssb_sirius_dash/tabs/frisok.py
  src/ssb_sirius_dash/tabs/generic.py
  src/ssb_sirius_dash/tabs/pi_memorizer.py
  src/ssb_sirius_dash/tabs/vof_foretak.py
Labels: documentation

#107 update docstring
  src/ssb_sirius_dash/setup/alert_handler.py
Labels: documentation

#112 Språk rydding
  pyproject.toml
  src/ssb_sirius_dash/control/framework.py
  src/ssb_sirius_dash/hb_method_aio.py
  src/ssb_sirius_dash/modals/hb_method.py
  src/ssb_sirius_dash/modals/kontroller.py
  src/ssb_sirius_dash/modals/kvalitetsindikatorer.py
  src/ssb_sirius_dash/modals/modal_functions.py
  src/ssb_sirius_dash/modals/visualiseringsbygger.py
  src/ssb_sirius_dash/setup/alert_handler.py
  src/ssb_sirius_dash/setup/app_setup.py
  src/ssb_sirius_dash/setup/functions.py
  src/ssb_sirius_dash/setup/main_layout.py
  src/ssb_sirius_dash/setup/variabelvelger.py
  src/ssb_sirius_dash/tabs/aarsregnskap.py
  src/ssb_sirius_dash/tabs/frisok.py
  src/ssb_sirius_dash/tabs/generic.py
  src/ssb_sirius_dash/tabs/pi_memorizer.py
  src/ssb_sirius_dash/tabs/vof_foretak.py
Labels: documentation, breaking

#114 Mypy fixes and run tests in container with python and R
  .devcontainer/devcontainer.json
  .github/workflows/tests.yml
  .gitignore
  poetry.lock
  pyproject.toml
  src/ssb_sirius_dash/control/framework.py
  src/ssb_sirius_dash/modals/hb_method.py
  src/ssb_sirius_dash/modals/kontroller.py
  src/ssb_sirius_dash/modals/kvalitetsindikatorer.py
  src/ssb_sirius_dash/modals/visualiseringsbygger.py
  src/ssb_sirius_dash/setup/app_setup.py
  src/ssb_sirius_dash/tabs/aarsregnskap.py
  src/ssb_sirius_dash/tabs/frisok.py
  src/ssb_sirius_dash/tabs/generic.py
  src/ssb_sirius_dash/tabs/pi_memorizer.py
  src/ssb_sirius_dash/tabs/vof_foretak.py
Labels: breaking

#115 Mypyfix
  pyproject.toml
  src/ssb_sirius_dash/control/__init__.py
  src/ssb_sirius_dash/control/framework.py
  src/ssb_sirius_dash/modals/__init__.py
  src/ssb_sirius_dash/modals/hb_method.py
  src/ssb_sirius_dash/modals/kontroller.py
  src/ssb_sirius_dash/modals/kvalitetsindikatorer.py
  src/ssb_sirius_dash/modals/visualiseringsbygger.py
  src/ssb_sirius_dash/setup/__init__.py
  src/ssb_sirius_dash/setup/alert_handler.py
  src/ssb_sirius_dash/setup/app_setup.py
  src/ssb_sirius_dash/setup/functions.py
  src/ssb_sirius_dash/setup/variabelvelger.py
  src/ssb_sirius_dash/tabs/__init__.py
  src/ssb_sirius_dash/tabs/frisok.py
  src/ssb_sirius_dash/tabs/generic.py
  src/ssb_sirius_dash/tabs/vof_foretak.py
  tests/test_import.py
Labels: documentation, refactoring

#116 Sphinx fix
  docs/reference.md
  src/ssb_sirius_dash/control/__init__.py
  src/ssb_sirius_dash/modals/__init__.py
  src/ssb_sirius_dash/setup/__init__.py
  src/ssb_sirius_dash/tabs/__init__.py
Labels: documentation

#113 Navngiving konsistens og litt rydding
  .gitignore
  demo/control_demo.py
  src/ssb_sirius_dash/control/framework.py
  src/ssb_sirius_dash/modals/control.py
  src/ssb_sirius_dash/modals/hb_method.py
  src/ssb_sirius_dash/modals/modal_functions.py
  src/ssb_sirius_dash/modals/quality_indicators.py
  src/ssb_sirius_dash/modals/visualizationbuilder.py
  src/ssb_sirius_dash/setup/alert_handler.py
  src/ssb_sirius_dash/setup/app_setup.py
  src/ssb_sirius_dash/setup/functions.py
  src/ssb_sirius_dash/setup/main_layout.py
  src/ssb_sirius_dash/setup/variableselector.py
  src/ssb_sirius_dash/tabs/aarsregnskap.py
  src/ssb_sirius_dash/tabs/bofregistry.py
  src/ssb_sirius_dash/tabs/freesearch.py
  src/ssb_sirius_dash/tabs/generic.py
  src/ssb_sirius_dash/tabs/pi_memorizer.py
  src/ssb_sirius_dash/utils/__init__.py
  src/ssb_sirius_dash/utils/functions.py
  tests/test_import.py
Labels: breaking, refactoring

#118 Fikser sphinx dokumentasjon
  KOMME_I_GANG.md
  docs/reference.md
  docs/ssb_sirius_dash.control.rst
  docs/ssb_sirius_dash.modals.rst
  docs/ssb_sirius_dash.setup.rst
  docs/ssb_sirius_dash.tabs.rst
  docs/ssb_sirius_dash.utils.rst
  poetry.lock
  pyproject.toml
Labels: documentation
